import Head from 'next/head'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/favicon.ico" />
      </Head>
        <Header/>
      <main className={styles.main}>
          <h1 className="text-3xl font-bold underline text-gray-700">
          Hello world!
          </h1>
      </main>
        <Footer/>
    </>
  )
}
